### ISSUE TITLE
Workflow für den automatischen Build der Dokumentation (public-ui.github.io)

### ISSUE THREAD

**Issue by deleonio** [public-ui/public-ui.github.io#222]
- [x] `dev`-Folder zukünftig einfach im Root `./` des Projektes liegt (`git mv`)
- [x] `dist`-Folder heißt zukünftig `docs`
- [ ] Workflow für `main` der einmal installiert und baut und den `docs`-Ordner pushed (GitHub-App)

**Comment by sdvg** [comment]
Abweichend von der o.g. Spec, stellen wir hier auf die [upload-pages-artifact](https://github.com/marketplace/actions/upload-github-pages-artifact)-Action umzustellen.
