### ISSUE TITLE
Doc: Dokumentation prüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/public-ui.github.io#231]
Komplette Doku einmal durchschauen und optische und Fehler in der Verwendung von KoliBri auflisten.

## Allgemein

Englische Version nicht ausreichend übersetzt (teilweise deutsch):
0.1 Header Links
0.2 Theme-Auswahl
0.3 Versionshinweise
0.4 Seitennavigation

![Image](https://github.com/user-attachments/assets/d69f6dd2-d445-437e-8d52-4a15a488508f)
![Image](https://github.com/user-attachments/assets/cfd71c5d-eae2-49bf-921a-9dd005c71d8d)

0.5 Sprachauswahl funktioniert teilweise fehlerhaft.
![Image](https://github.com/user-attachments/assets/153154a1-9f91-4787-a98a-984abac3c40b)
Beispiel:
- Öffne https://public-ui.github.io/docs/next/concepts/test (ggf. Incognito verwenden)
- Klicke mehrfach auf den Sprach-Toggle

### Deutsch

1.1.1 Leerer Alert: 
![Image](https://github.com/user-attachments/assets/cf2b802f-5dc7-4f85-8b4e-1810674fcb52)

1.1.2 Links und Abbrs brechen mitten im Satz mehrfach um:
![Image](https://github.com/user-attachments/assets/6c3b662f-8a87-435a-be8f-fe50c0de8cc0)
![Image](https://github.com/user-attachments/assets/53f33180-866a-49a6-8721-944beab6a417)
![Image](https://github.com/user-attachments/assets/11aa5022-8240-4094-ae33-4170e3b18184)
![Image](https://github.com/user-attachments/assets/29515d70-1de9-4c7c-8f77-2f31dcfc6cb7)

1.1.3 Typo: 
![Image](https://github.com/user-attachments/assets/fbbc4a20-5723-48a1-ba78-909eab85928a)

1.1.4 Unsauberer Umbruch:
![Image](https://github.com/user-attachments/assets/7f1d750b-fbff-43a1-aeb7-23936d43a78a)

1.1.5 Fehlender Inhalt (?)
![Image](https://github.com/user-attachments/assets/f3ccdef7-6b45-4d3d-adb9-b546daa317cf)

### Englisch

1.2.1 Fehlerhafter Alert-Content:
![Image](https://github.com/user-attachments/assets/1f2e7dfe-0f7c-40df-8c19-6d443348fb06)

1.2.2 Ebenfalls diverse Links, die Paragraphs unterbrechen:

![Image](https://github.com/user-attachments/assets/7da9d97b-012d-41e1-96b4-83f687f11840)

### Deutsch

2.1.1 Lizenz verlinkt auf 404: 
![Image](https://github.com/user-attachments/assets/8998e99b-4b43-4e97-85e5-61ec325c41f5)

2.1.2 Fehlender Whitespace:
![Image](https://github.com/user-attachments/assets/17b96085-ba67-4b5d-9445-6478191d457d)

2.1.3 Veralteter Inhalt bzgl. Theming (in JS) und Schema:
![Image](https://github.com/user-attachments/assets/2103a547-21b7-455d-b2dc-5bc7322481c1)

### Englisch

2.2.1 Lizenz verlinkt auch hierauf 404
2.2.2 "TS-File" verlinkt auf 404:
![Image](https://github.com/user-attachments/assets/10b21d10-fe94-45b0-9b9a-db8df511f2ac)

### Deutsch

3.1.0 Was ist der Unterschied zwischen "React" und "Vite + React"? Die Beschreibungen unterscheiden sich minimal, beide sind aber bundler-agnostisch.
Was ist der Unterschied zwischen "ohne Framework" und "statische Webseite"? Gehören die Schritte nicht zusammen? Sollten wir hier primär eine Einbindung ohne CDN beschreiben?

3.1.1 "Neues Projekt" verweist noch auf `npm init` - stattdessen direkt Templates verlinken?
![Image](https://github.com/user-attachments/assets/0df2e987-4392-447f-b5d1-cfdb82851333)

3.1.2 Schritt "Modul einbinden" (bei **allen** Setups, wiederholt sich) sollte für gewöhnlich nicht notwendig sein:
![Image](https://github.com/user-attachments/assets/b4ce1d8e-925d-4789-abfd-88270ceeed80)

### Englisch

3.2.1 Leere Karte: 
![Image](https://github.com/user-attachments/assets/35bfba1d-8c40-4ef7-a2e8-e5b223624b75)

3.2.2 Inhalte teilweise auf Deutsch: Sollte einmal komplett geprüft und übersetzt werden.

3.2.3. Alle Punkte von "Deutsch" treffen auch hier zu.

### Deutsch

4.1.1 Übersicht der Pakete listet veraltete Pakete: core, schema, angular v11-14
Angular v18 fehlt. Vielleicht noch erwähnenswert: CLI und theme-default

4.1.2 Fehlerhafte HTML-Formatierung:
![Image](https://github.com/user-attachments/assets/dc532b5e-6833-469b-bcc7-3fa65b72a44b)

4.1.3 Typo: 
![Image](https://github.com/user-attachments/assets/9440d94d-67aa-4785-be02-ecc30d0a372c)

4.1.4 Angular nur noch ab v15 unterstützt:
![Image](https://github.com/user-attachments/assets/6ce0e414-19b1-48fe-9d94-73bfb498c065)

4.1.5 SSR Logos haben kein sichtbares Label:
![Image](https://github.com/user-attachments/assets/b1da5ea2-3726-4201-857c-d52e63e3c964)

### Englisch

4.2.1 Beschreibung zu Vue nicht übersetzt: 
![Image](https://github.com/user-attachments/assets/bafafd3c-5d8a-49a2-b9ac-c8fd8a23c88c)

4.2.2 Alle Punkte von "Deutsch" treffen auch hier zu.

### Deutsch

5.1.1 Stackblitz verwendet noch KoliBri 1
5.1.1 Das Codesandbox-Beispiel wirkt unsauber, weil die Icons fehlen
![Image](https://github.com/user-attachments/assets/baf47298-d720-4ee6-a218-36494388cd6a)

### Englisch

5.2.1 Die Links sind auf Deutsch
![Image](https://github.com/user-attachments/assets/ebe49780-90bf-4c40-b37f-e33358f5dfa0)

5.2.2 Die Code-Beispiele ebenfalls:
![Image](https://github.com/user-attachments/assets/baf47298-d720-4ee6-a218-36494388cd6a)

5.2.3 Alle Punkte von "Deutsch" treffen auch hier zu.

## Architektur

6. Sollte (für beide Sprachversionen) komplett überarbeitet werden. Hier ist noch die Rede von Verdaccio, Storybook, Schema, Core, etc.

### Deutsch und Englisch

7.1.1 Sollten wir die "Veralteten Eigenschaften" und "Veraltete Komponenten" aus der V2-Doku entfernen? Mittlerweile für die meisten nicht mehr relevant, wir können stattdessen auf MIGRATION.md verweisen. Ich würde mich hier ganz auf den Ist-Stand fokussieren.

### Englisch

7.2.1 Sternchentext ist nicht übersetzt.
![Image](https://github.com/user-attachments/assets/2199fb73-6338-4afc-986a-239a84f6b500)

### Beide Sprachversionen

8.1.1 Screenshot zeigt noch Storybook
![Image](https://github.com/user-attachments/assets/e8fa46a2-6684-4070-93b3-71eeb2d7062e)

8.1.2 Link "Modularisierung" führ zu 404:
![Image](https://github.com/user-attachments/assets/ba5c4335-5b1f-47a5-9966-53378fd49ee9)

### Deutsch

8.2.1 Mehrere fehlerhafte Zeilenumbrüche durch Links:
![Image](https://github.com/user-attachments/assets/ac47bfd8-006b-43ae-a1b3-cd2406756ed3)

### Englisch

8.3.1 Link-Labels fehlen: 
![Image](https://github.com/user-attachments/assets/10cc7bd4-2a93-4e1c-9caa-fb5a4785e214)

8.3.2 KolDetails-Labels fehlen:
![Image](https://github.com/user-attachments/assets/a1d6cefc-c57a-4107-b894-6e932b62c1de)

**Comment by chrisalat** [comment]
Gelöst:

- [ ] Allgemein
- [ ] Willkommen-Seite
- [ ] FAQ
- [ ] Erste Schritte
- [ ] Frameworks
- [ ] Playground
- [ ] Architektur
- [ ] Eigenschaften
- [ ] Theming
