### ISSUE TITLE
Fehlt: Kacheln für "Drawer" und "SingleSelect" auf der Komponenten-Übersichtsseite + Erstellung der Dokumentationsseiten

### ISSUE THREAD

**Issue by laske185** [public-ui/public-ui.github.io#241]
**Beschreibung:**
Auf der Komponenten-Übersichtsseite fehlen aktuell die Kacheln für die folgenden Komponenten:
- **Drawer**
- **SingleSelect**

Zusätzlich existieren die Dokumentationsseiten für diese beiden Komponenten bisher nicht. Daher müssen zunächst die entsprechenden Seiten erstellt werden.

**Aufgaben:**
1. Erstellung der Dokumentationsseite für die **Drawer**-Komponente.
2. Erstellung der Dokumentationsseite für die **SingleSelect**-Komponente.
3. Hinzufügen der Kacheln für **Drawer** und **SingleSelect** auf der Komponenten-Übersichtsseite.
4. Verlinken der Kacheln auf die neu erstellten Dokumentationsseiten.

**Akzeptanzkriterien:**
- Zwei neue Dokumentationsseiten für "Drawer" und "SingleSelect" existieren
  - Die ReadMe gibt es jeweils. Es muss noch die Doku-Seite generiert werden.
- Zwei neue Kacheln auf der Komponenten-Übersichtsseite wurden hinzugefügt.
  - Eine Kachel für die "Drawer"-Komponente.
  - Eine Kachel für die "SingleSelect"-Komponente.
- Beide Kacheln verlinken auf die neu erstellten Dokumentationsseiten.

**Zusätzliche Hinweise:**
- Die neuen Kacheln sollten dem bestehenden Design der Übersichtsseite entsprechen.
- Die Inhalte der neuen Dokumentationsseiten können an bestehenden Komponenten-Dokumentationen ausgerichtet werden.
- Folgeticket von https://github.com/public-ui/kolibri/issues/6887

**Comment by anicyne** [comment]
Siehe #6956

**Comment by laske185** [comment]
Wir müssen auf neues Release warten.

**Comment by deleonio** [comment]
2.1.9er Release ist raus.
